---
abstract: 'Real-time web framework'
author:
  - 'Sebastian Riedel <sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious
no_index:
  directory:
    - t
    - inc
    - examples
    - t
  package:
    - Mojo::Server::PSGI::_IO
    - Mojo::Util::_Guard
requires:
  IO::Socket::IP: '0.37'
  Sub::Util: '1.41'
  perl: '5.016'
resources:
  IRC:
    url: irc://irc.libera.chat/#mojo
    web: https://web.libera.chat/#mojo
  bugtracker: https://github.com/mojolicious/mojo/issues
  homepage: https://mojolicious.org
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/mojolicious/mojo.git
version: '9.22'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
